apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    app: voting-app
spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        app: voting-app
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust          
          volumeMounts:
            - mountPath: /postgres/pv
              name: postgres-vol
      volumes:  
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: voting-app-pvc
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
