apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: voting-app
spec:
  template:
    metadata:
      name: redis-pod
      labels:
        app: voting-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
