apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    app: voting-app
spec:
  template:
    metadata:
      name: result-app-pod
      labels:
        app: voting-app
    spec:
      containers:
        - name: result-app
          image: raghadhabib/result:latest
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
