apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voting-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
  selector:
    matchLabels:
      name: pv


  